name: Release Gachapon Machine

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-2022

    env:
      PLUGIN_NAME: GachaPlugin

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Build (Release)
      run: dotnet build --configuration Release

    - name: Create / update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: .\${{ env.PLUGIN_NAME }}\bin\x64\Release\${{ env.PLUGIN_NAME }}\latest.zip
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
